name: 👥 Auto Assign Reviewers

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  assign-reviewers:
    name: Assign Reviewers
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: 👥 Auto assign reviewers
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto-assign.yml'
