name: 🏷️ Auto Label PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  label-pr:
    name: Auto Label Based on Files
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: 🏷️ Apply labels based on changed files
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true

  label-by-size:
    name: Label by PR Size
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: 📏 Label based on PR size
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size: xs'
          xs_max_size: 10
          s_label: 'size: s'
          s_max_size: 100
          m_label: 'size: m'
          m_max_size: 500
          l_label: 'size: l'
          l_max_size: 1000
          xl_label: 'size: xl'
          fail_if_xl: false
          message_if_xl: >
            Este PR é muito grande! Considere dividi-lo em PRs menores para facilitar a revisão.
          github_api_url: 'https://api.github.com'
